apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  name: ingress-nginx

## About Namespace
# https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/