# Service Account for the "controller"
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.12.0
  name: ingress-nginx
  namespace: ingress-nginx
---

# Service Account for the "admission webhook"

# admission webhook = 
#   - validating webhook that ingress-nginx includes
#   - helps to create or update Ingress objects (unless webhook configuration is removed)
apiVersion: v1
automountServiceAccountToken: true
# AutomountServiceAccountToken indicates whether pods running as this service account should 
#   have an API token automatically mounted. Can be overridden at the pod level.
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.12.0
  name: ingress-nginx-admission
  namespace: ingress-nginx

## About Service Accounts
# https://kubernetes.io/docs/concepts/security/service-accounts/